inputdir: /fast/users/szyskam_c/work/projects/Chromium/UPN292/CRcount  # source of fastq files (subfolders allowed)
workdir: /fast/users/szyskam_c/scratch/projects/UPN292 # here your results are created
snakedir: /fast/users/szyskam_c/snakes/projects/scMut
samples: # here go all your samples
  patients: # samples are expected as AML013_D_R1.fastq and AML013_D_R2.fastq
    - RA080657
    - WU090661
  tumor:
    - DBMmini
    # - Rel1
    # - CR2
    # - Rel2
  normal:
    - DTCmini   # if more than one, the first normal will be used as default for tumor-sample
  reads:
    - R1
    - R2
  separation: '_'
  compression:
    - gz
    - bz2
setup:  
  run: PE
  phred: 33
  readlength: 125  # neccessary???
  library: SureSelect  # have to be found at bed_files/SureSelect/<build>/SS_<library_version>_<build>_<Padded | Covered>[_nochr].bed
  library_version: HAEv7

#### ABSOLUTE PATHS ############
paths:
  mystatic: /fast/groups/ag_damm/work/ref/
  bihstatic: /fast/projects/cubit/current/static_data
  scripts: scripts/ # folder relative to snakedir
#### REF SECTION ###############
ref:
  build: hg38
  hg19:
    genome_path: genome/gatk/b37
    genome: genome/gatk/b37/human_g1k_v37.fasta
    candidates: /fast/users/szyskam_c/work/utils/bulltools/known_sites/candidate_genes_aml.txt
    dbsnp: annotation/gatk/b37/dbsnp_138.b37.vcf
    dbsnp_all: annotation/gatk/b37/All_20180423.vcf
    dbsnp_common: annotation/gatk/b37/common_all_20180423.vcf
    gold_standard_indels: annotation/gatk/b37/Mills_and_1000G_gold_standard.indels.b37.vcf
    phase1k_indels: annotation/gatk/b37/1000G_phase1.indels.b37.vcf
    # bed_file: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Covered_nochr.bed
    # bed_file_pad: bed_files/SureSelect/hg19/SS_HAEv6r2_hg19_Padded_nochr.bed
  hg38:
    genome_path: genome/gatk/hg38/
    genome: genome/gatk/hg38/hg38.fasta
    dbsnp: annotation/gatk/hg38/dbsnp_138.hg38.vcf
    dbsnp_all: annotation/gatk/hg38/All_20180418.vcf
    dbsnp_common: annotation/gatk/hg38/common_all_20180418.vcf
    gold_standard_indels: annotation/gatk/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf
    phase1k_indels: annotation/gatk/hg38/1000G_phase1.snps.high_confidence.hg38.vcf # seems to work instead of indels (acc. to GATK blog: https://gatkforums.broadinstitute.org/gatk/discussion/6800/known-sites-for-indel-realignment-and-bqsr-in-hg38-bundle)
    # bed_file: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Covered.bed
    # bed_file_pad: bed_files/SureSelect/hg38/SS_HAEv7_hg38_Padded.bed
#### TOOLS SECTION ##############
tools:
  gatk: gatk # 
  gatk3: java -jar /fast/users/szyskam_c/work/utils/gatk3.8/GenomeAnalysisTK.jar -T
  annovar: perl /fast/users/szyskam_c/tools/annovar_2018
scripts:
  prettifyBED : prettify_BEDcoverage.awk
  format_bed_coverage: formatCoverage.sh
  anno_format: anno_format.mawk
  expand_info: expand_info.sh
  merge_anno: merge_anno.py
  filter_csv: filter_exome_wFlankingSeq.sh
fastq:
  threads: 2
qc:
  samplefactor: 1
trim:
  program: trimmomatic
  trimming: True
  threads: 12
  mode: 
    - "AVGQUAL:20"
    - "SLIDINGWINDOW:4:15"
    - "LEADING:3"
  output_name:
    - "trim"
    - "trim_UP"
dedup:
  threads: 4
alignment:
  tool: bwa
  threads: 16
bamindex:
  threads: 1
realignGATK:
  threads: 16
recalib:
  run: True
  threads: 12
  known_sites: dbsnp_common   # which dbsnp database to use beside gold_standard_indels and phase1k
cover_bed:
  histo_steps: "0 1 10 15 50 100 120 200 500 1000 1500 2000 2500"
varscan:
  threads: 8
  min-coverage: 1
  min-var-freq: 0.01
  min-freq-for-hom: 0.75
  normal-purity: 0.95
  tumor-purity: 0.8
  p-value: 0.99
  somatic-p-value: 0.05
annovar:
  threads: 4
  path_to_humandb: annotation/annovar/humandb
  annofiles:
    - refGene
    - cytoBand
    - genomicSuperDups
    - esp6500_all
    - esp6500siv2_all
    # - 1000g2010nov_all
    - 1000g2014oct_all
    - gnomad_exome
    - exac03
    - dbscsnv11
    # - snp131
    # - snp131NonFlagged
    # - snp138
    - snp138NonFlagged
    # - avsnp138
    - avsnp150
    - cosmic70
    # - clinvar_20150629
    # - clinvar_20170905
    - clinvar_20190305
    - ljb23_pp2hdiv
    - ljb23_sift
    - ljb26_all
    - spidex
    - icgc21

EBFilter:
  run: False
  pon_list: /fast/users/szyskam_c/work/static/ref/PoN/AML_Pon.txt
  use_cache: False
  cache_folder: /fast/users/szyskam_c/work/static/ref/PoN/AML_cache
  threads: 
    generateCache: 31
    EBscore: 12
  params:
    sep: tab
    map_quality: 20
    base_quality: 15
    fitting_penalty: 0.5
filter:
    bull:  # changed from -name: bull  # this is also the extension used in the filtered output (_bull.csv)
      run: False
      path: bullinger.py # filters are expected in scripts/filters
      params: 
        TM2_limit: 4
    daniel: 
      run: True
      path: daniel.py
      params:
        TM2_limit: 4
